#!/bin/bash
PATH="`ruby -e 'puts Gem.user_dir'`/bin:$PATH"
GIT_REPO=$HOME/connectordb_static.git
TMP_GIT_CLONE=$HOME/tmp/connectordb.com
PUBLIC_WWW=/www/connectordb.com/static

git clone $GIT_REPO $TMP_GIT_CLONE
cd $TMP_GIT_CLONE && jekyll build -s $TMP_GIT_CLONE -d $PUBLIC_WWW
cd ~ && rm -rf $TMP_GIT_CLONE

find $PUBLIC_WWW -type f -print0 | xargs -0 chmod 666
find $PUBLIC_WWW -type d -print0 | xargs -0 chmod 777

exit
