package permissions

// Default represents the default permissions to use in ConnectorDB. They are what is used when ConnectorDB's config has "default"
// as its "permissions" field value
var Default = Permissions{
	Version: 1,
	Watch:   true,

	// Here we disallow names that would conflict with the ConnectorDB frontend
	DisallowedNames: []string{"support", "www", "api", "app", "favicon.ico", "robots.txt", "sitemap.xml", "join", "login", "user", "admin", "nobody", "root"},

	// Allow an arbitrary number of users by default
	MaxUsers: -1,

	// Only one role is required by ConnectorDB: "nobody". This is the role automatically assigned to random
	// people that visit the web server. This is obviously not ideal.
	//
	// By Default, ConnectorDB creates 3 roles:
	// - nobody:
	//     Can't access anything - is greeted with the landing page and a login prompt
	// - user:
	//     Can create its own streams/devices, can read "public" users/devices, but cannot write
	//     anything public, and cannot read anything private.
	// - admin:
	//     Total control: Can read/write anything anywhere. Also has permissions to create new users.
	//
	// This default is very privacy-oriented, and is therefore recommended for private/family/IOT ConnectorDB instances.
	//
	// Remember that the "full" and "none" access levels are built-in (ie, don't need to be defined)
	UserRoles: map[string]*UserRole{
		"nobody": &UserRole{
			Join:                false,
			JoinRole:            "user",
			JoinDisabledMessage: "You must be logged in to add users",

			// Ain't nobody have access
			DeviceRole: DeviceRole{
				PrivateAccessLevel: "none",
				PublicAccessLevel:  "none",
				UserAccessLevel:    "none",
				SelfAccessLevel:    "none",
			},
		},
		"user": &UserRole{
			Join:                false,
			JoinRole:            "user",
			JoinDisabledMessage: "You must be logged in as admin to add users",

			CanBePrivate: true,

			CreateDeviceDefaults: DeviceDefaults{
				Enabled:      true,
				Public:       false,
				IsVisible:    true,
				UserEditable: true,
			},

			// ... Not bad
			DeviceRole: DeviceRole{
				PrivateAccessLevel: "none",
				PublicAccessLevel:  "userpublic",
				UserAccessLevel:    "userself",
				SelfAccessLevel:    "userself",
			},
		},
		"admin": &UserRole{
			Join:                true,
			JoinRole:            "user",
			JoinDisabledMessage: "Join is disabled",

			CanBePrivate: true,

			CreateDeviceDefaults: DeviceDefaults{
				Enabled:      true,
				Role:         "none",
				Public:       false,
				IsVisible:    true,
				UserEditable: true,
			},
			CreateUserDefaults: UserDefaults{
				Role:   "user",
				Public: true,
			},

			// ACCESS ALL THE THINGS
			DeviceRole: DeviceRole{
				CanCountUsers:      true,
				CanCountDevices:    true,
				CanCountStreams:    true,
				PrivateAccessLevel: "fullnp",
				PublicAccessLevel:  "fullnp",
				UserAccessLevel:    "fullnp",
				SelfAccessLevel:    "fullnp",
			},
		},
	},

	DeviceRoles: map[string]*DeviceRole{
		"none": &DeviceRole{
			PrivateAccessLevel: "none",
			PublicAccessLevel:  "none",
			UserAccessLevel:    "none",
			SelfAccessLevel:    "fulldevice",
		},
		"reader": &DeviceRole{
			PrivateAccessLevel: "devicereader",
			PublicAccessLevel:  "devicereader",
			UserAccessLevel:    "devicereader",
			SelfAccessLevel:    "fulldevice",
		},
		"writer": &DeviceRole{
			PrivateAccessLevel: "devicewriter",
			PublicAccessLevel:  "devicewriter",
			UserAccessLevel:    "devicewriter",
			SelfAccessLevel:    "fulldevice",
		},
		"user": &DeviceRole{
			CanCountUsers:      true,
			CanCountDevices:    true,
			CanCountStreams:    true,
			PrivateAccessLevel: "fulldownlink",
			PublicAccessLevel:  "fulldownlink",
			UserAccessLevel:    "fulldownlink",
			SelfAccessLevel:    "full",
		},
	},

	AccessLevels: map[string]*AccessLevel{
		"userpublic": &AccessLevel{
			CanCreateUser:   false,
			CanCreateDevice: false,
			CanCreateStream: false,
			CanDeleteUser:   false,
			CanDeleteDevice: false,
			CanDeleteStream: false,

			CanListUsers:   false,
			CanListDevices: true,
			CanListStreams: true,

			ReadAccess:  "publicread",
			WriteAccess: "none",
		},
		"userself": &AccessLevel{
			CanCreateUser:   false,
			CanCreateDevice: true,
			CanCreateStream: true,
			CanDeleteUser:   false,
			CanDeleteDevice: true,
			CanDeleteStream: true,

			CanListUsers:   false,
			CanListDevices: true,
			CanListStreams: true,

			ReadAccess:  "selfread",
			WriteAccess: "selfwrite",
		},
		"devicereader": &AccessLevel{
			CanCreateUser:   false,
			CanCreateDevice: false,
			CanCreateStream: false,
			CanDeleteUser:   false,
			CanDeleteDevice: false,
			CanDeleteStream: false,

			CanListUsers:   false,
			CanListDevices: true,
			CanListStreams: true,

			ReadAccess:  "deviceread",
			WriteAccess: "none",
		},
		"devicewriter": &AccessLevel{
			CanCreateUser:   false,
			CanCreateDevice: false,
			CanCreateStream: false,
			CanDeleteUser:   false,
			CanDeleteDevice: false,
			CanDeleteStream: false,

			CanListUsers:   false,
			CanListDevices: true,
			CanListStreams: true,

			ReadAccess:  "deviceread",
			WriteAccess: "devicewrite",
		},
		"fulldevice": &AccessLevel{
			CanCreateUser:   true,
			CanCreateDevice: true,
			CanCreateStream: true,
			CanDeleteUser:   false,
			CanDeleteDevice: true,
			CanDeleteStream: true,

			CanListUsers:   true,
			CanListDevices: true,
			CanListStreams: true,

			ReadAccess:  "full",
			WriteAccess: "fulldevicewrite",
		},
		"fulldownlink": &AccessLevel{
			CanCreateUser:   true,
			CanCreateDevice: true,
			CanCreateStream: true,
			CanDeleteUser:   true,
			CanDeleteDevice: true,
			CanDeleteStream: true,

			CanListUsers:   true,
			CanListDevices: true,
			CanListStreams: true,

			ReadAccess:  "full",
			WriteAccess: "fulldownlinkwrite",
		},
		"fullnp": &AccessLevel{
			CanCreateUser:   true,
			CanCreateDevice: true,
			CanCreateStream: true,
			CanDeleteUser:   true,
			CanDeleteDevice: true,
			CanDeleteStream: true,

			CanListUsers:   true,
			CanListDevices: true,
			CanListStreams: true,

			ReadAccess:  "selfread",
			WriteAccess: "full",
		},
	},

	RWAccess: map[string]*RWAccess{
		"publicread": &RWAccess{
			CanAccessUser:                   true,
			CanAccessDevice:                 true,
			CanAccessStream:                 true,
			CanAccessNonUserEditableDevices: false,
			CanAccessStreamData:             true,
			CanAccessStreamDownlink:         true,
			UserName:                        true,
			UserNickname:                    true,
			UserEmail:                       false,
			UserDescription:                 true,
			UserIcon:                        true,
			UserRole:                        false,
			UserPublic:                      true,
			UserPassword:                    false,
			DeviceName:                      true,
			DeviceNickname:                  true,
			DeviceDescription:               true,
			DeviceIcon:                      true,
			DeviceAPIKey:                    false,
			DeviceEnabled:                   true,
			DeviceIsVisible:                 true,
			DeviceUserEditable:              false,
			DevicePublic:                    true,
			DeviceRole:                      false,
			StreamName:                      true,
			StreamNickname:                  true,
			StreamDescription:               true,
			StreamIcon:                      true,
			StreamSchema:                    true,
			StreamDatatype:                  true,
			StreamEphemeral:                 true,
			StreamDownlink:                  true,
		},
		"selfwrite": &RWAccess{
			CanAccessUser:                   true,
			CanAccessDevice:                 true,
			CanAccessStream:                 true,
			CanAccessNonUserEditableDevices: false,
			CanAccessStreamData:             true,
			CanAccessStreamDownlink:         true,
			UserName:                        false,
			UserNickname:                    true,
			UserEmail:                       true,
			UserDescription:                 true,
			UserIcon:                        true,
			UserRole:                        false,
			UserPublic:                      true,
			UserPassword:                    true,
			DeviceName:                      false,
			DeviceNickname:                  true,
			DeviceDescription:               true,
			DeviceIcon:                      true,
			DeviceAPIKey:                    true,
			DeviceEnabled:                   true,
			DeviceIsVisible:                 true,
			DeviceUserEditable:              false,
			DevicePublic:                    true,
			DeviceRole:                      true,
			StreamName:                      false,
			StreamNickname:                  true,
			StreamDescription:               true,
			StreamIcon:                      true,
			StreamSchema:                    true,
			StreamDatatype:                  true,
			StreamEphemeral:                 true,
			StreamDownlink:                  true,
		},
		"selfread": &RWAccess{
			CanAccessUser:                   true,
			CanAccessDevice:                 true,
			CanAccessStream:                 true,
			CanAccessNonUserEditableDevices: true,
			CanAccessStreamData:             true,
			CanAccessStreamDownlink:         true,
			UserName:                        true,
			UserNickname:                    true,
			UserEmail:                       true,
			UserDescription:                 true,
			UserIcon:                        true,
			UserRole:                        true,
			UserPublic:                      true,
			UserPassword:                    false,
			DeviceName:                      true,
			DeviceNickname:                  true,
			DeviceDescription:               true,
			DeviceIcon:                      true,
			DeviceAPIKey:                    true,
			DeviceEnabled:                   true,
			DeviceIsVisible:                 true,
			DeviceUserEditable:              true,
			DevicePublic:                    true,
			DeviceRole:                      true,
			StreamName:                      true,
			StreamNickname:                  true,
			StreamDescription:               true,
			StreamIcon:                      true,
			StreamSchema:                    true,
			StreamDatatype:                  true,
			StreamEphemeral:                 true,
			StreamDownlink:                  true,
		},
		"deviceread": &RWAccess{
			CanAccessUser:                   true,
			CanAccessDevice:                 true,
			CanAccessStream:                 true,
			CanAccessNonUserEditableDevices: true,
			CanAccessStreamData:             true,
			CanAccessStreamDownlink:         true,
			UserName:                        true,
			UserNickname:                    true,
			UserEmail:                       true,
			UserDescription:                 true,
			UserIcon:                        true,
			UserRole:                        true,
			UserPublic:                      true,
			UserPassword:                    false,
			DeviceName:                      true,
			DeviceNickname:                  true,
			DeviceDescription:               true,
			DeviceIcon:                      true,
			DeviceAPIKey:                    false,
			DeviceEnabled:                   true,
			DeviceIsVisible:                 true,
			DeviceUserEditable:              true,
			DevicePublic:                    true,
			DeviceRole:                      true,
			StreamName:                      true,
			StreamNickname:                  true,
			StreamDescription:               true,
			StreamIcon:                      true,
			StreamSchema:                    true,
			StreamDatatype:                  true,
			StreamEphemeral:                 true,
			StreamDownlink:                  true,
		},
		"devicewrite": &RWAccess{
			CanAccessUser:                   true,
			CanAccessDevice:                 true,
			CanAccessStream:                 true,
			CanAccessNonUserEditableDevices: false,
			CanAccessStreamData:             false,
			CanAccessStreamDownlink:         true,
			UserName:                        false,
			UserNickname:                    true,
			UserEmail:                       true,
			UserDescription:                 true,
			UserIcon:                        true,
			UserRole:                        false,
			UserPublic:                      true,
			UserPassword:                    false,
			DeviceName:                      true,
			DeviceNickname:                  true,
			DeviceDescription:               true,
			DeviceIcon:                      true,
			DeviceAPIKey:                    false,
			DeviceEnabled:                   true,
			DeviceIsVisible:                 true,
			DeviceUserEditable:              true,
			DevicePublic:                    true,
			DeviceRole:                      false,
			StreamName:                      true,
			StreamNickname:                  true,
			StreamDescription:               true,
			StreamIcon:                      true,
			StreamSchema:                    true,
			StreamDatatype:                  true,
			StreamEphemeral:                 true,
			StreamDownlink:                  true,
		},
		"fulldevicewrite": &RWAccess{
			CanAccessUser:                   true,
			CanAccessDevice:                 true,
			CanAccessStream:                 true,
			CanAccessNonUserEditableDevices: false,
			CanAccessStreamData:             true,
			CanAccessStreamDownlink:         false,
			UserName:                        false,
			UserNickname:                    true,
			UserEmail:                       true,
			UserDescription:                 true,
			UserIcon:                        true,
			UserRole:                        false,
			UserPublic:                      true,
			UserPassword:                    false,
			DeviceName:                      false,
			DeviceNickname:                  true,
			DeviceDescription:               true,
			DeviceIcon:                      true,
			DeviceAPIKey:                    true,
			DeviceEnabled:                   true,
			DeviceIsVisible:                 true,
			DeviceUserEditable:              true,
			DevicePublic:                    true,
			DeviceRole:                      false,
			StreamName:                      false,
			StreamNickname:                  true,
			StreamDescription:               true,
			StreamIcon:                      true,
			StreamSchema:                    true,
			StreamDatatype:                  true,
			StreamEphemeral:                 true,
			StreamDownlink:                  true,
		},
		"fulldownlinkwrite": &RWAccess{
			CanAccessUser:                   true,
			CanAccessDevice:                 true,
			CanAccessStream:                 true,
			CanAccessNonUserEditableDevices: true,
			CanAccessStreamData:             false,
			CanAccessStreamDownlink:         true,
			UserName:                        true,
			UserNickname:                    true,
			UserEmail:                       true,
			UserDescription:                 true,
			UserIcon:                        true,
			UserRole:                        true,
			UserPublic:                      true,
			UserPassword:                    true,
			DeviceName:                      true,
			DeviceNickname:                  true,
			DeviceDescription:               true,
			DeviceIcon:                      true,
			DeviceAPIKey:                    true,
			DeviceEnabled:                   true,
			DeviceIsVisible:                 true,
			DeviceUserEditable:              true,
			DevicePublic:                    true,
			DeviceRole:                      true,
			StreamName:                      true,
			StreamNickname:                  true,
			StreamDescription:               true,
			StreamIcon:                      true,
			StreamSchema:                    true,
			StreamDatatype:                  true,
			StreamEphemeral:                 true,
			StreamDownlink:                  true,
		},
	},
}
