#!/bin/bash
PATH="`ruby -e 'puts Gem.user_dir'`/bin:$PATH"
GIT_REPO=$HOME/git/public.git
TMP_GIT_CLONE=$HOME/git/tmp/public
PUBLIC_WWW=$HOME/www/public

git clone $GIT_REPO $TMP_GIT_CLONE
cd $TMP_GIT_CLONE && jekyll build -s $TMP_GIT_CLONE -d $PUBLIC_WWW
cd ~ && rm -rf $TMP_GIT_CLONE

find $PUBLIC_WWW -type f -print0 | xargs -0 chmod 755
find $PUBLIC_WWW -type d -print0 | xargs -0 chmod 755

exit
