#!/bin/bash

# Create a heedy database with a special test app, which has api key "testkey"
rm -rf ../../testdb
../../heedy create ../../testdb --noserver --username=test --password=test --testapp=testkey

# Start the database in the background
../../heedy start ../../testdb --verbose

# Wait for the port to be open
# https://stackoverflow.com/questions/27599839/how-to-wait-for-an-open-port-with-netcat
echo "Waiting for heedy to start..."
while ! nc -z localhost 1324; do   
  sleep 0.5
done

# Run tests
pytest -x --cov=heedy --timeout=50
status=$?

../../heedy stop ../../testdb
rm -rf ../../testdb

exit $status