// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package timeseries

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonFcf5e2abDecodeGithubComHeedyHeedyPluginsTimeseriesBackendTimeseries(in *jlexer.Lexer, out *DatapointArray) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(DatapointArray, 0, 8)
			} else {
				*out = DatapointArray{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 *Datapoint
			if in.IsNull() {
				in.Skip()
				v1 = nil
			} else {
				if v1 == nil {
					v1 = new(Datapoint)
				}
				(*v1).UnmarshalEasyJSON(in)
			}
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonFcf5e2abEncodeGithubComHeedyHeedyPluginsTimeseriesBackendTimeseries(out *jwriter.Writer, in DatapointArray) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			if v3 == nil {
				out.RawString("null")
			} else {
				(*v3).MarshalEasyJSON(out)
			}
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v DatapointArray) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonFcf5e2abEncodeGithubComHeedyHeedyPluginsTimeseriesBackendTimeseries(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v DatapointArray) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonFcf5e2abEncodeGithubComHeedyHeedyPluginsTimeseriesBackendTimeseries(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *DatapointArray) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonFcf5e2abDecodeGithubComHeedyHeedyPluginsTimeseriesBackendTimeseries(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *DatapointArray) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonFcf5e2abDecodeGithubComHeedyHeedyPluginsTimeseriesBackendTimeseries(l, v)
}
func easyjsonFcf5e2abDecodeGithubComHeedyHeedyPluginsTimeseriesBackendTimeseries1(in *jlexer.Lexer, out *Datapoint) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "t":
			out.Timestamp = float64(in.Float64())
		case "dt":
			out.Duration = float64(in.Float64())
		case "d":
			if m, ok := out.Data.(easyjson.Unmarshaler); ok {
				m.UnmarshalEasyJSON(in)
			} else if m, ok := out.Data.(json.Unmarshaler); ok {
				_ = m.UnmarshalJSON(in.Raw())
			} else {
				out.Data = in.Interface()
			}
		case "a":
			out.Actor = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonFcf5e2abEncodeGithubComHeedyHeedyPluginsTimeseriesBackendTimeseries1(out *jwriter.Writer, in Datapoint) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"t\":"
		out.RawString(prefix[1:])
		out.Float64(float64(in.Timestamp))
	}
	if in.Duration != 0 {
		const prefix string = ",\"dt\":"
		out.RawString(prefix)
		out.Float64(float64(in.Duration))
	}
	{
		const prefix string = ",\"d\":"
		out.RawString(prefix)
		if m, ok := in.Data.(easyjson.Marshaler); ok {
			m.MarshalEasyJSON(out)
		} else if m, ok := in.Data.(json.Marshaler); ok {
			out.Raw(m.MarshalJSON())
		} else {
			out.Raw(json.Marshal(in.Data))
		}
	}
	if in.Actor != "" {
		const prefix string = ",\"a\":"
		out.RawString(prefix)
		out.String(string(in.Actor))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Datapoint) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonFcf5e2abEncodeGithubComHeedyHeedyPluginsTimeseriesBackendTimeseries1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Datapoint) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonFcf5e2abEncodeGithubComHeedyHeedyPluginsTimeseriesBackendTimeseries1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Datapoint) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonFcf5e2abDecodeGithubComHeedyHeedyPluginsTimeseriesBackendTimeseries1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Datapoint) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonFcf5e2abDecodeGithubComHeedyHeedyPluginsTimeseriesBackendTimeseries1(l, v)
}
